### ISSUE TITLE
1.18无法连接到服务器

### ISSUE THREAD

**Issue by 3375884492** [neko-craft/NekoMaid#11]
paper

[14:59:29 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.Minecraft
Server.getServerConnection()
[14:59:29 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[14:59:29 WARN]:        at Uniporter-1.3.2-SNAPSHOT.jar//cn.apisium.uniporter.ut
il.ReflectionFinder.getServerConnectionMethodFromClass(ReflectionFinder.java:55)

[14:59:29 WARN]:        at Uniporter-1.3.2-SNAPSHOT.jar//cn.apisium.uniporter.ut
il.ReflectionFinder.getServerConnection(ReflectionFinder.java:62)
[14:59:29 WARN]:        at Uniporter-1.3.2-SNAPSHOT.jar//cn.apisium.uniporter.ut
il.ReflectionFinder.findChannelFutures(ReflectionFinder.java:24)
[14:59:29 WARN]:        at Uniporter-1.3.2-SNAPSHOT.jar//cn.apisium.uniporter.Un
iporter.findBoostrapChannelFutures(Uniporter.java:207)
[14:59:29 WARN]:        at Uniporter-1.3.2-SNAPSHOT.jar//cn.apisium.uniporter.Un
iporter.attachChannelHandler(Uniporter.java:220)
[14:59:29 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.r
un(CraftTask.java:101)
[14:59:29 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftSchedu
ler.mainThreadHeartbeat(CraftScheduler.java:483)
[14:59:29 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServe
r.java:1211)
[14:59:29 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(Mi
necraftServer.java:317)
[14:59:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:59:29 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass(
)" because "connection" is null
[14:59:29 WARN]:        at Uniporter-1.3.2-SNAPSHOT.jar//cn.apisium.uniporter.ut
il.ReflectionFinder.findChannelFutures(ReflectionFinder.java:26)
[14:59:29 WARN]:        at Uniporter-1.3.2-SNAPSHOT.jar//cn.apisium.uniporter.Un
iporter.findBoostrapChannelFutures(Uniporter.java:207)
[14:59:29 WARN]:        at Uniporter-1.3.2-SNAPSHOT.jar//cn.apisium.uniporter.Un
iporter.attachChannelHandler(Uniporter.java:220)
[14:59:29 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.r
un(CraftTask.java:101)
[14:59:29 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftSchedu
ler.mainThreadHeartbeat(CraftScheduler.java:483)
[14:59:29 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServe
r.java:1211)
[14:59:29 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(Mi
necraftServer.java:317)
[14:59:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ShirasawaSama** [comment]
请更新Uniporter到最新版
