### ISSUE TITLE
直接访问 / 会报错

### ISSUE THREAD

**Issue by iceBear67** [neko-craft/NekoMaid#2]
```
[02:29:58 WARN]: cn.apisium.uniporter.router.exception.IllegalHttpStateException
[02:29:58 WARN]:        at cn.apisium.uniporter.router.api.Config.lambda$null$23(Config.java:297)
[02:29:58 WARN]:        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[02:29:58 WARN]:        at cn.apisium.uniporter.router.api.Config.lambda$findRoute$24(Config.java:297)
[02:29:58 WARN]:        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
[02:29:58 WARN]:        at cn.apisium.uniporter.router.api.Config.findRoute(Config.java:276)
[02:29:58 WARN]:        at cn.apisium.uniporter.router.util.RouteResolver.getRoute(RouteResolver.java:26)
[02:29:58 WARN]:        at cn.apisium.uniporter.router.handler.HttpServerHandler.channelRead0(HttpServerHandler.java:40)
[02:29:58 WARN]:        at cn.apisium.uniporter.router.handler.HttpServerHandler.channelRead0(HttpServerHandler.java:23)
[02:29:58 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:29:58 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[02:29:58 WARN]:        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:29:58 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:29:58 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[02:29:58 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:29:58 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:29:58 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[02:29:58 WARN]:        at cn.apisium.uniporter.Decoder.decode(Decoder.java:38)
[02:29:58 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
[02:29:58 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
[02:29:58 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:29:58 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:29:58 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:29:58 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:29:58 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[02:29:58 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[02:29:58 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
[02:29:58 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
[02:29:58 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
[02:29:58 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[02:29:58 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[02:29:58 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[02:29:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```
插件列表:

```
[02:30:56 INFO]: Plugins (5): MiaoChat, NekoMaid, PlaceholderAPI, spark, Uniporter
```

NekoMaid , UniPorter 均为最新    

~~其实不会影响什么但是考虑到有玩家可能直接http访问好不爽啊顺便问一下UniPorter里面的route handler: static是指服务端核心目录的static文件夹吗~~

**Comment by ShirasawaSama** [comment]
这是已知问题，下个版本会修复

**Comment by iceBear67** [comment]
好的谢谢

**Comment by ShirasawaSama** [comment]
UniPorter里面的route handler: static是指 `plugins/Uniporter/static` 目录

**Comment by iceBear67** [comment]
(((   
话说这个报错会是因为没有这个目录产生的吗

**Comment by ShirasawaSama** [comment]
@iceBear67 不是

默认这个错误是仅在 `debug: true` 时才会显示.

现在应该是忘记判断了

**Comment by iceBear67** [comment]
好吧

**Comment by ShirasawaSama** [comment]
@lj2000lj

**Comment by lj2000lj** [comment]
Fixed
