### ISSUE TITLE
无法连接到服务器

### ISSUE THREAD

**Issue by AlexanderMC8533** [neko-craft/NekoMaid#3]
能打开网页，但空白
将127.0.0.1换成正确的IP地址，无法打开，即使没改链接，也依旧无内容

**Comment by ShirasawaSama** [comment]
请给出服务器类型及版本

**Comment by AlexanderMC8533** [comment]
插件+Forge模组（MonistMC）1.12.2
顺便反馈：服务器IP一直是127.0.0.1，而不是公网IP





------------------ 原始邮件 ------------------
发件人: Shirasawa ***@***.***&gt;
发送时间: 2021年7月26日 19:34
收件人: neko-craft/NekoMaid ***@***.***&gt;
抄送: AlexanderMC8533 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[neko-craft/NekoMaid] 无法连接到服务器 (#3)





 
请给出服务器类型及版本

**Comment by ShirasawaSama** [comment]
@AlexanderMC8533

后台有报错吗

本插件及前置插件是最新版本吗（0.0.3）

地址问题请修改插件配置文件中的 `hostname` 项为真正的服务器链接地址

**Comment by AlexanderMC8533** [comment]
已经更新到3



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月28日(周三) 晚上6:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [neko-craft/NekoMaid] 无法连接到服务器 (#3)




 
@AlexanderMC8533
 
后台有报错吗
 
本插件及前置插件是最新版本吗（0.0.3）
 
地址问题请修改插件配置文件中的 hostname 项为真正的服务器链接地址

**Comment by AlexanderMC8533** [comment]
[39;0m java.lang.NullPointerException: null
at cn.apisium.uniporter.Uniporter.registerHandler(Uniporter.java:101) ~[?:?]
at cn.apisium.nekomaid.NekoMaid.onEnable(NekoMaid.java:154) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) [JavaPluginLoader.class:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:?]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:477) [CraftServer.class:?]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418) [CraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:389) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月28日(周三) 晚上6:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [neko-craft/NekoMaid] 无法连接到服务器 (#3)




 
@AlexanderMC8533
 
后台有报错吗
 
本插件及前置插件是最新版本吗（0.0.3）
 
地址问题请修改插件配置文件中的 hostname 项为真正的服务器链接地址

**Comment by ShirasawaSama** [comment]
前置插件 `Uniporter` 是最新版吗

**Comment by AlexanderMC8533** [comment]
是1.2版，目前找到的最新的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月28日(周三) 晚上7:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [neko-craft/NekoMaid] 无法连接到服务器 (#3)




 
前置插件 Uniporter 是最新版吗

**Comment by ShirasawaSama** [comment]
@AlexanderMC8533 最新版是 [1.2.5](https://github.com/Apisium/Uniporter/releases/tag/1.2.5-SNAPSHOT)

**Comment by AlexanderMC8533** [comment]
***@***.***



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月28日(周三) 晚上7:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [neko-craft/NekoMaid] 无法连接到服务器 (#3)




 
@AlexanderMC8533 最新版是 1.2.5

**Comment by ShirasawaSama** [comment]
@AlexanderMC8533 看不到邮件内容, 最好可以直接到github上回复

**Comment by AlexanderMC8533** [comment]
> @AlexanderMC8533 看不到邮件内容, 最好可以直接到github上回复

2570892032在qq邮箱上
