### ISSUE TITLE
无法通过NekoMaid封禁玩家

### ISSUE THREAD

**Issue by Dongyanmio** [neko-craft/NekoMaid#37]
无法通过NekoMaid封禁玩家，执行封禁后会报错

`[11:26:20 FATAL]: Thread Netty Epoll Server IO #1 failed main thread check: player kick
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.kickPlayer(CraftPlayer.java:506) ~[patched_1.17.1.jar:git-Purpur-1428]
        at cn.apisium.nekomaid.builtin.PlayerList.lambda$null$3(PlayerList.java:87) ~[NekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.Emitter.emit(Emitter.java:123) ~[NekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoSocket.onEvent(SocketIoSocket.java:309) ~[NekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoSocket.onPacket(SocketIoSocket.java:329) ~[NekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoClient.lambda$setup$1(SocketIoClient.java:163) ~[NekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.socketio.server.parser.IOParser$Decoder.add(IOParser.java:99) ~[NekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoClient.lambda$setup$2(SocketIoClient.java:171) ~[NekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.Emitter.emit(Emitter.java:123) ~[NekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.EngineIoSocket.emit(EngineIoSocket.java:190) ~[NekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.EngineIoSocket.onPacket(EngineIoSocket.java:406) ~[NekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.EngineIoSocket.lambda$setTransport$10(EngineIoSocket.java:306) ~[NekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.Emitter.emit(Emitter.java:123) ~[NekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.Transport.onPacket(Transport.java:102) ~[NekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.Transport.onData(Transport.java:111) ~[NekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.transport.WebSocket.lambda$new$0(WebSocket.java:26) ~[NekoMaid.jar:?]
        at cn.apisium.nekomaid.libs.io.socket.engineio.server.Emitter.emit(Emitter.java:123) ~[NekoMaid.jar:?]
        at cn.apisium.netty.engineio.EngineIoHandler.channelRead0(EngineIoHandler.java:91) ~[NekoMaid.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[11:26:20 WARN]: java.lang.IllegalStateException: Asynchronous player kick!
[11:26:20 WARN]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)
[11:26:20 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.kickPlayer(CraftPlayer.java:506)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.builtin.PlayerList.lambda$null$3(PlayerList.java:87)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.Emitter.emit(Emitter.java:123)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoSocket.onEvent(SocketIoSocket.java:309)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoSocket.onPacket(SocketIoSocket.java:329)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoClient.lambda$setup$1(SocketIoClient.java:163)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.socketio.server.parser.IOParser$Decoder.add(IOParser.java:99)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoClient.lambda$setup$2(SocketIoClient.java:171)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.Emitter.emit(Emitter.java:123)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.EngineIoSocket.emit(EngineIoSocket.java:190)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.EngineIoSocket.onPacket(EngineIoSocket.java:406)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.EngineIoSocket.lambda$setTransport$10(EngineIoSocket.java:306)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.Emitter.emit(Emitter.java:123)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.Transport.onPacket(Transport.java:102)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.Transport.onData(Transport.java:111)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.transport.WebSocket.lambda$new$0(WebSocket.java:26)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.Emitter.emit(Emitter.java:123)
[11:26:20 WARN]:        at NekoMaid.jar//cn.apisium.netty.engineio.EngineIoHandler.channelRead0(EngineIoHandler.java:91)
[11:26:20 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[11:26:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:26:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:26:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:26:20 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[11:26:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:26:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:26:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:26:20 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[11:26:20 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[11:26:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:26:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:26:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:26:20 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[11:26:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:26:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:26:20 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[11:26:20 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[11:26:20 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[11:26:20 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[11:26:20 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[11:26:20 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:26:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)`

**Comment by ShirasawaSama** [comment]
Fixed in 0.3.3
