### ISSUE TITLE
[Bug]無法解壓縮資料包

### ISSUE THREAD

**Issue by kalenimoru** [neko-craft/NekoMaid#43]
# Describe the bug

解壓縮資料包會失敗。

## To Reproduce

1，隨便找一個資料包上傳到\world\datapack\任意自料夾名稱，以這個例子來說是[Terralith](https://www.stardustlabs.net/datapacks#Terralith)
2，用NekoMaid的檔案管理功能解壓縮(decompress)
3，失敗

## Log

[00:53:33 WARN]: java.nio.file.NoSuchFileException: .\world\datapacks\Terralith\data\c
[00:53:33 WARN]:        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[00:53:33 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[00:53:33 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[00:53:33 WARN]:        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
[00:53:33 WARN]:        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
[00:53:33 WARN]:        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.builtin.FilesManager.lambda$null$8(FilesManager.java:160)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.Client.lambda$onWithAck$1(Client.java:81)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.Emitter.emit(Emitter.java:123)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoSocket.onEvent(SocketIoSocket.java:309)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoSocket.onPacket(SocketIoSocket.java:329)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoClient.lambda$setup$1(SocketIoClient.java:163)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.socketio.server.parser.IOParser$Decoder.add(IOParser.java:99)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.socketio.server.SocketIoClient.lambda$setup$2(SocketIoClient.java:171)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.Emitter.emit(Emitter.java:123)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.EngineIoSocket.emit(EngineIoSocket.java:190)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.EngineIoSocket.onPacket(EngineIoSocket.java:406)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.EngineIoSocket.lambda$setTransport$10(EngineIoSocket.java:306)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.Emitter.emit(Emitter.java:123)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.Transport.onPacket(Transport.java:102)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.Transport.onData(Transport.java:111)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.transport.WebSocket.lambda$new$0(WebSocket.java:26)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.nekomaid.libs.io.socket.engineio.server.Emitter.emit(Emitter.java:123)
[00:53:33 WARN]:        at NekoMaid.jar//cn.apisium.netty.engineio.EngineIoHandler.channelRead0(EngineIoHandler.java:91)
[00:53:33 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[00:53:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:53:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:53:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:53:33 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[00:53:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:53:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:53:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:53:33 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[00:53:33 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[00:53:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:53:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:53:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:53:33 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[00:53:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[00:53:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:53:33 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[00:53:33 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[00:53:33 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[00:53:33 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[00:53:33 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[00:53:33 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[00:53:33 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[00:53:33 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:53:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

## Information

- Server: purpur-1.19.4-1976
- Plugin version: 0.3.3
- Uniporter version: 1.3.4-SNAPSHOT

**Comment by ShirasawaSama** [comment]
有空了我看一下
