### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Jhesterccj** [neko-craft/NekoMaid#48]
版本：1.20.1
核心：purpur-2025
2023-08-08 14:03:47,681 Async Chat Thread - #19 ERROR An exception occurred processing Appender NekoMaid java.util.NoSuchElementException
        at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:362)
        at java.base/java.util.ArrayDeque.remove(ArrayDeque.java:523)
        at com.google.common.collect.EvictingQueue.add(EvictingQueue.java:112)
        at NekoMaid.jar//cn.apisium.nekomaid.builtin.Terminal.append(Terminal.java:82)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:531)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
        at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:154)
        at org.apache.logging.slf4j.Log4jLogger.log(Log4jLogger.java:370)
        at net.kyori.adventure.text.logger.slf4j.WrappingComponentLoggerImpl.info(WrappingComponentLoggerImpl.java:1432)
        at com.destroystokyo.paper.console.TerminalConsoleCommandSender.sendMessage(TerminalConsoleCommandSender.java:23)
        at com.destroystokyo.paper.console.TerminalConsoleCommandSender.sendRawMessage(TerminalConsoleCommandSender.java:18)
        at org.bukkit.craftbukkit.v1_20_R1.command.CraftConsoleCommandSender.sendMessage(CraftConsoleCommandSender.java:27)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.platform.type.BukkitCommandSender.sendMessage(BukkitCommandSender.kt:36)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.module.chat.impl.DefaultComponent.sendTo(DefaultComponent.kt:61)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.api.impl.BukkitComponentManager.sendComponent(BukkitComponentManager.kt:66)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.util.BukkitUtilKt.sendComponent(BukkitUtil.kt:102)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:200)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:47)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35)
        at TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72)
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414)
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100)
        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2498)
        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2654)
        at net.minecraft.server.network.PlayerConnection.lambda$handleChat$18(PlayerConnection.java:2326)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Jhesterccj** [comment]
> 2023-08-08 17:24:33,275 defaultEventLoopGroup-15-2 ERROR An exception occurred processing Appender NekoMaid java.util.NoSuchElementException
        at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:362)
        at java.base/java.util.ArrayDeque.remove(ArrayDeque.java:523)
        at com.google.common.collect.EvictingQueue.add(EvictingQueue.java:112)
        at NekoMaid.jar//cn.apisium.nekomaid.builtin.Terminal.append(Terminal.java:82)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:162)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
        at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1330)
        at org.bukkit.craftbukkit.v1_20_R1.util.ForwardLogHandler.publish(ForwardLogHandler.java:36)
        at java.logging/java.util.logging.Logger.log(Logger.java:980)
        at java.logging/java.util.logging.Logger.doLog(Logger.java:1007)
        at java.logging/java.util.logging.Logger.log(Logger.java:1030)
        at java.logging/java.util.logging.Logger.info(Logger.java:1803)
        at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.GeyserSpigotLogger.info(GeyserSpigotLogger.java:69)
        at Geyser-Spigot.jar//org.geysermc.geyser.session.GeyserSession$1.disconnected(GeyserSession.java:1056)
        at Geyser-Spigot.jar//com.github.steveice10.packetlib.event.session.DisconnectedEvent.call(DisconnectedEvent.java:56)
        at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:146)
        at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.lambda$disconnect$1(TcpSession.java:286)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:756)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:731)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1352)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:749)
        at io.netty.channel.AbstractChannelHandlerContext.access$1200(AbstractChannelHandlerContext.java:61)
        at io.netty.channel.AbstractChannelHandlerContext$11.run(AbstractChannelHandlerContext.java:732)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Jhesterccj** [comment]
023-08-08 17:18:08,520 Server thread ERROR An exception occurred processing Appender NekoMaid java.util.NoSuchElementException
        at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:362)
        at java.base/java.util.ArrayDeque.remove(ArrayDeque.java:523)
        at com.google.common.collect.EvictingQueue.add(EvictingQueue.java:112)
        at NekoMaid.jar//cn.apisium.nekomaid.builtin.Terminal.append(Terminal.java:82)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:162)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2022)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1875)
        at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:175)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1770)
        at net.minecraft.server.players.PlayerList.a(PlayerList.java:1408)
        at net.minecraft.server.players.PlayerList.a(PlayerList.java:1402)
        at net.minecraft.server.AdvancementDataPlayer.a(AdvancementDataPlayer.java:254)
        at net.minecraft.advancements.CriterionTrigger$a.a(CriterionTrigger.java:35)
        at net.minecraft.advancements.critereon.CriterionTriggerAbstract.a(CriterionTriggerAbstract.java:73)
        at net.minecraft.advancements.critereon.CriterionTriggerInventoryChanged.a(CriterionTriggerInventoryChanged.java:57)
        at net.minecraft.advancements.critereon.CriterionTriggerInventoryChanged.a(CriterionTriggerInventoryChanged.java:53)
        at net.minecraft.server.level.EntityPlayer$2.slotChanged(EntityPlayer.java:393)
        at net.minecraft.world.inventory.Container.a(Container.java:307)
        at net.minecraft.world.inventory.Container.d(Container.java:244)
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3382)
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
        at net.minecraft.server.TickTask.run(TickTask.java:18)
        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1366)
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1343)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1336)
        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1314)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
        at java.base/java.lang.Thread.run(Thread.java:833)
